# Generated by Django 5.1.2 on 2025-05-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='время обновления')),
                ('status', models.CharField(max_length=255, verbose_name='Номер группы')),
            ],
            options={
                'verbose_name': 'Статус выполнения',
                'verbose_name_plural': 'Статусы выполнения',
                'ordering': ['id', 'status'],
            },
        ),
    ]
