# Generated by Django 5.1.2 on 2025-05-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('answer', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('generatedTask', '0001_initial'),
        ('group', '0001_initial'),
        ('userTaskStatus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Почта')),
                ('full_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('is_active', models.BooleanField(default=False, verbose_name='активный пользователь')),
                ('is_staff', models.BooleanField(default=False, verbose_name='персонал')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='админ')),
                ('answers', models.ManyToManyField(blank=True, related_name='Answers', to='answer.answer', verbose_name='Ответы')),
                ('generated_tasks', models.ManyToManyField(blank=True, related_name='GeneratedTasks', to='generatedTask.generatedtask', verbose_name='Варианты')),
                ('group_id', models.ManyToManyField(blank=True, related_name='custom_user_groups', to='group.group', verbose_name='Группа')),
                ('groups', models.ManyToManyField(blank=True, related_name='auth_user_groups', to='group.group', verbose_name='Группы')),
                ('task_status', models.ManyToManyField(blank=True, related_name='TaskStatus', to='userTaskStatus.taskstatus', verbose_name='Статус задания')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='auth_user_permissions', to='auth.permission', verbose_name='Права пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['id', 'email'],
            },
        ),
    ]
