# Generated by Django 5.1.2 on 2025-05-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='время обновления')),
                ('title', models.CharField(max_length=255, verbose_name='Название задания')),
                ('view', models.TextField(verbose_name='Отображение задания')),
                ('data_task', models.TextField(verbose_name='Содержание задания')),
                ('tempalates', models.ManyToManyField(blank=True, related_name='task_templates', to='templates.templates', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['id', 'title'],
            },
        ),
    ]
